{
 "title": "[how2web] Autoscaling Dashboard",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "About Us",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <img src=\"https://raw.githubusercontent.com/hellojanam/how2web/refs/heads/main/img/how2web_ch.png\" alt=\"CloudHero Logo\" style=\"width: 250px; display: block; margin: 0 auto;\">\n  <p style=\"color: white; font-size: 18px; margin-top: -150px;\">\n    We are certified cloud experts that help you make the most of Kubernetes, AWS, and Data & Analytics.\n  </p>\n</div>\n"
   }
  },
  {
   "title": "Node Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(pod, namespace) (\n  rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", pod!=\"\"}[5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Status?",
   "type": "stat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)-sum(cluster_autoscaler_scaled_down_nodes_total)"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\"})"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count)",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count)\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count)\n"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\"})"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "stat",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})/sum(cluster_autoscaler_nodes_count)*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale)"
    }
   ]
  },
  {
   "title": "No. of unscheduled pods",
   "type": "stat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "timeseries",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total)",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "timeseries",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\"})\n",
     "legendFormat": "not started"
    }
   ]
  }
 ]
}