apiVersion: v1
kind: Service
metadata:
  name: how2web
spec:
  selector:
    app: nginx  # Matches the labels from the Deployment
  ports:
    - protocol: TCP
      port: 80  # The port your service will expose
      targetPort: 80  # The container port inside the pod
  type: ClusterIP  # Default type, exposes the service only within the cluster
