version: '3'
services:
  node-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=testdb
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command:
      - --mysql-native-password=ON
      - --log-error-verbosity=3    
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb  