apiVersion: apps/v1
kind: Deployment
metadata:
  name: how2web
spec:
  selector:
    matchLabels:
      app: how2web-app
  template:
    metadata:
      labels:
        app: how2web-app
    spec:
      containers:
        - name: how2web-app
          image: iamjanam/sample-node-api:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql-0.mysql.default.svc.cluster.local
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_NAME
              value: testdb
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"       
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: testdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
