apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: how2web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: how2web
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # Set to 0 for immediate scaling up
      policies:
        - type: Percent
          value: 100  # Double the number of replicas
          periodSeconds: 15  # Evaluates every 15 seconds
    scaleDown:
      stabilizationWindowSeconds: 30  # Wait before scaling down
      policies:
        - type: Percent
          value: 50  # Scale down by 50%
          periodSeconds: 60
